### ISSUE TITLE
How to Deploy Kubernetes on Linode with Rancher 2.3 Proposed Changes

### ISSUE THREAD

**Issue by kodumbeats** [linode/docs#2979]
Link: https://linode.com/docs/kubernetes/how-to-deploy-kubernetes-on-linode-with-rancher-2-x/
## Issue
While provisioning the cluster on version 1.16, the following error indicates a problem with the deployment of the API server, and prevents any use of the Rancher UI:
```
[controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [$IP]: Get https://localhost:6443/healthz: dial tcp [::1]:6443: connect: connection refused, log: ]
```
Investigating the docker logs on any of the worker nodes reveals:
```
$ docker logs kube-apiserver
Error: invalid argument "PersistentLocalVolumes=true,VolumeScheduling=true,CSINodeInfo=true,CSIDriverRegistry=true,BlockVolume=true,CSIBlockVolume=true" for "--feature-gates" flag: unrecognized feature gate: VolumeScheduling
```
According to the [k8s docs](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/), the VolumeScheduling feature flag is in General Availability (GA) for k8s clusters running version 1.13+, and for GA features (per docs):
> The corresponding feature gate is no longer needed

Removing `VolumeScheduling=true` from the `kube-api` and `kubelet` services in the YAML file corrects this behavior and allows for a successfully provisioned cluster.

## Suggested Fix
Remove `VolumeScheduling=true` from the services snippet in step 12 of "Provision a Cluster":
```
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: "30000-32767"
      extra_args:
        feature-gates: "PersistentLocalVolumes=true,CSINodeInfo=true,CSIDriverRegistry=true,BlockVolume=true,CSIBlockVolume=true"
    kubelet:
      fail_swap_on: false
      extra_args:
        cloud-provider: "external"
        feature-gates: "PersistentLocalVolumes=true,CSINodeInfo=true,CSIDriverRegistry=true,BlockVolume=true,CSIBlockVolume=true"
    kube-controller:
      extra_args:
        cloud-provider: "external"
```
