### ISSUE TITLE
States should be more compact

### ISSUE THREAD

**Issue by ferricoxide** [linode/docs#393]
Looking at the `salt-states-apache-mysql-php-fail2ban.md` file (this is the source file for the [Salt States to Install Apache, MySQL, PHP (LAMP), and Fail2ban](https://www.linode.com/docs/applications/salt/salt-states-apache-mysql-php-fail2ban) article?), the state definitions for the `pkg.installed` components could be written a lot more compactly. Typically, the  `lamp.sls` would be written more like

```
lamp-stack:
  pkg.installed:
  - pkgs:
    - mysql-server
    - php5
    - php-pear
    - php5-mysql
```

and the `extras.sls` state would be written more like

```
fail2ban:
  pkg.installed
```

Or, if maintaining separate states for the LAMP and fail2ban installs wasn't a requirement, a single state of the form:

```
fail2ban-stack:
  pkg.installed:
  - pkgs:
    - mysql-server
    - php5
    - php-pear
    - php5-mysql
    - fail2ban
```

Could be used, instead.
